export const INITIALIZE_NETWORK = 'INITIALIZE_NETWORK';
export const SET_APP_COMPONENT_STATE = 'SET_APP_COMPONENT_STATE'; // 3 states -> 1) form 2) pending events 3) data recieved 
export const SET_DEPOSIT_EVENT_TX_DATA = 'SET_DEPOSIT_EVENT_TX_DATA';
export const SET_WITHDRAWAL_EVENT_TX_DATA = 'SET_WITHDRAWAL_EVENT_TX_DATA';
